# Generated by Django 4.2.6 on 2023-10-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('duracion', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='docente',
            name='carrera_id',
        ),
        migrations.AddField(
            model_name='comunicado',
            name='fecha_publicacion',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Carrera',
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
    ]
