# Generated by Django 4.2.6 on 2023-10-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_comunicado_fecha_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='detalle',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
