# Generated by Django 4.2.6 on 2023-10-23 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0006_alter_entidad_options_alter_entidad_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entidad',
        ),
    ]
