# Generated by Django 4.2.6 on 2023-10-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0007_delete_entidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='detalle',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
