# Generated by Django 4.2.6 on 2023-10-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0008_alter_comunicado_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='detalle_corto',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
