# Generated by Django 4.2.6 on 2023-10-24 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miapp', '0009_comunicado_detalle_corto'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunicados_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
