# Generated by Django 4.2.6 on 2023-10-24 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0011_alter_comunicado_creador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunicado',
            name='duracion',
        ),
    ]
