# Generated by Django 4.2.6 on 2023-10-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0012_remove_comunicado_duracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes/')),
            ],
        ),
    ]
