# Generated by Django 4.2.6 on 2023-10-24 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0013_entidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comunicado',
            old_name='creador',
            new_name='publicado_por',
        ),
        migrations.RenameField(
            model_name='entidad',
            old_name='imagen',
            new_name='logo',
        ),
        migrations.RemoveField(
            model_name='comunicado',
            name='fecha_actual',
        ),
        migrations.AddField(
            model_name='comunicado',
            name='fecha_modificacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='entidad',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='fecha_publicacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
