# Generated by Django 4.2.6 on 2023-10-24 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miapp', '0015_remove_comunicado_publicado_por_comunicado_creador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunicado',
            name='creador',
        ),
        migrations.AddField(
            model_name='comunicado',
            name='publicado_por',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunicados_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
